In [ ]:
 print("hello world")


hello world


In [ ]:
print("hey")

hey


In [ ]:
print("hi", end="-")
print("murari")

hi-murari


In [ ]:
x=20
print(type(x))

<class 'int'>


In [ ]:
x="saini"
print(type(x))

<class 'str'>


In [ ]:
gendar="male"
print(type("gender"))

<class 'str'>


In [ ]:
gender='female'
print(type("gender"))

<class 'str'>


In [ ]:
address='''basant vihar
jaipur 333305'''
print(type(address))

<class 'str'>


In [ ]:
#this is basic of phyton

# this is define code

'''  this is a multi line comment

defint'''

In [ ]:
#basic,print,end
# variaable , string,multi linr string, comment,


In [ ]:
# string formatting



In [ ]:
year=2025
company="regeex"
print("currnt year is",year,"company is=",company)

currnt year is 2025 company is= regeex


In [ ]:
year=2025
comapny="saini"

y = f"currnt year is {year} company is {comapny}"

print(y)

currnt year is 2025 company is saini


In [ ]:
print(y)

currnt year is 2025 company is saini


In [ ]:
username="murari"
msg=f"my name is {username}"
print(msg)

username="abhisek"
print(msg)

my name is murari
my name is murari


In [ ]:
year=2025
comapny="saini"

y = f"currnt year is {year} company is {comapny}"


In [ ]:
"current year is{} company is ={}".format(2025,company  )

'current year is2025 company is =saini'

In [ ]:











# day 2 24 april








In [ ]:
10/3


3.3333333333333335

In [ ]:
10//3

3

In [ ]:
3.332+10

13.332

In [ ]:
10%3

1

In [ ]:
2**3
#2*2*2

8

In [ ]:
3**4

81

In [ ]:

2*2/4-1

0.0

In [ ]:
3+2*2/4-1

3.0

In [ ]:
'''priorty in python

**
* / // %

+ -




'''

In [ ]:
# comparison operator => true/false

10>2
#  >, >= , <, <=, ==, !=

In [ ]:
x=10
x+5
print(x)

10


In [ ]:
x=10
x=x+5
print(x)

15


In [ ]:
x=10
x+=5   #x=x+5   , +=, -=, %=
print(x)

15


In [ ]:
x=26
x%=4  # x=x%4
print(x)

2


In [ ]:
  # logical operator    alll condiction are true than true otherthan false
10>2  and 10>5

True

In [ ]:
10>2 or 10>50  # one condiction is true than true

True

In [ ]:
10>2 or 10>5 and 10>70

True

In [ ]:
# membership operator
# used to checck whether some data is avilable into some other datatype



In [ ]:
"r"in "regex"

True

In [ ]:
"R"not in "regex"

True

In [ ]:
# string indexing and slicing

'''
STRING : COLLECCTION OF CCHARCTER IN A CERTAIN ORDER
-5-4-3-2-1  [NEGETIVE INDEX]
REGEX
01234 [POSITIVE INDEX]

'''

In [ ]:
state="RAJASTHAN"
print(state[-3])

A


In [ ]:
# slicing operator : extract data from a variable or a string based on the index position
# [start : stop : [step=1]]

In [ ]:
state="RAJASTHAN"
print(state[0:4])

RAJA


In [ ]:
state="RAJASTHAN"
print(state[2:6])

JAST


In [ ]:
state="RAJASTHAN"
print(state[:8])

RAJASTHA


In [ ]:
state="RAJASTHAN"
print(state[:5])

RAJAS


In [ ]:
state="RAJASTHAN"
print(state[::1])

RAJASTHAN


In [ ]:
state="RAJASTHAN"
print(state[::-1])

NAHTSAJAR


In [ ]:
state="RAJASTHAN"
print(state[0:-4])

RAJAS


In [ ]:
state="RAJASTHAN"
print(state[3:-1])

ASTHA


In [ ]:
state="RAJASTHAN"
print(state[-5:-1])

STHA


In [ ]:
state="RAJASTHAN"
print(state[-5:7])

STH


In [ ]:
state="RAJASTHAN"
print(state[-5:2])

In [ ]:





# days 3  25/04/2025








In [ ]:
#conditional statement
'''

if(condition){

statement

   statement
}

if(condition):
  statement



  '''

IndentationError: unexpected indent (<ipython-input-107-eb5524e92bb5>, line 18)

In [ ]:
if(True):
  print("hey")

hey


In [ ]:
if(False):
  print("hey")

In [ ]:
num=10
if(num==10):
  print("number is 10")

print("hey")  # outside of statement


number is 10
hey


In [ ]:
num=12
if(num==10):
  print("number is 10")
else:
  print("condiction is false")

condiction is false


In [ ]:
num=5
if(num%2==0):
  print(" number is even")
else:
  print("number is odd")

number is odd


In [ ]:
# num=8  2,3
# 2 = number is diveded
# 3 =number is diveded by 3

num=8
if(num%2==0):
  print("number diveded by 2")

else:
  print("condiction is false")

if(num%3==0):
  print("number diveded by 3")
else:
  print("comdiction is false")

number diveded by 2
comdiction is false


In [ ]:
num=7
if(num%2==0):
  print("number diveded by 2")

elif(num%3==0):
  print("number diveded by 3")
else:
  print("condiction is false")


condiction is false


In [ ]:
a=7
b=5
c=8

if(a<=b and a<=c):
  print("smallest is a")

elif(b<=a and b<=c):
  print("b is smallest")

else:
  print("smallest is c")

b is smallest


In [ ]:
num=12
if(num%2==0 and num%3==0):
  print(6)

elif(num%2==0):
  print(2)

elif(num%3==0):
  print(3)

else:
  print("number not divided by 2 and 3")

6


In [ ]:
age=52

if(age>=60):
  print("senior citizen")

elif(age>=35):
  print("yong")

elif(age>=25):
  print("adult")

else:
  print("child")


yong


In [ ]:
# nested if-else
# condition ke andar koi condiction


In [ ]:
#account
# aadhar card , pan card


In [ ]:
num=4
if(num>2):
  print("greter than 2")

else:
  print("smaller than 2")

greter than 2


In [ ]:
num=6
if(num>2):
  print("greter than 2")
  if(num>4):
    print("greter thsn 2 and 4")

else:
  print("smaller than 2")

greter than 2
greter thsn 2 and 4


In [ ]:



#day 4

#26/04/2025






In [ ]:
#loops =loops statement


In [ ]:
# for(int i=0; i<5; i++)
# for i in rang (0,5)


In [ ]:
for i in range(0,5):
  print("hey",i)

hey 0
hey 1
hey 2
hey 3
hey 4


In [ ]:
for i in range(1,5):
  print("hey",i)

hey 1
hey 2
hey 3
hey 4


In [ ]:
for i in range(1,7,2):
  print("hey",i)

hey 1
hey 3
hey 5


In [ ]:
for i in range(1,10,2):
  print("hey",i)

hey 1
hey 3
hey 5
hey 7
hey 9


In [ ]:
for i in range(5,1,-1):
  print("hey",i)

hey 5
hey 4
hey 3
hey 2


In [ ]:
total=0
for i in range(1,8):

  total=total+i  #total=total=1
  print("hey",i,total)

hey 1 1
hey 2 3
hey 3 6
hey 4 10
hey 5 15
hey 6 21
hey 7 28


In [ ]:
total=0
for i in range(95,57,-1):
  total=total+i
  print("hey",i, total)

hey 95 95
hey 94 189
hey 93 282
hey 92 374
hey 91 465
hey 90 555
hey 89 644
hey 88 732
hey 87 819
hey 86 905
hey 85 990
hey 84 1074
hey 83 1157
hey 82 1239
hey 81 1320
hey 80 1400
hey 79 1479
hey 78 1557
hey 77 1634
hey 76 1710
hey 75 1785
hey 74 1859
hey 73 1932
hey 72 2004
hey 71 2075
hey 70 2145
hey 69 2214
hey 68 2282
hey 67 2349
hey 66 2415
hey 65 2480
hey 64 2544
hey 63 2607
hey 62 2669
hey 61 2730
hey 60 2790
hey 59 2849
hey 58 2907


In [ ]:

for i in range(1,7):
  if(i%2==0):
    print("diveded by 2  :",i)

diveded by 2  : 2
diveded by 2  : 4
diveded by 2  : 6


In [ ]:
total=0
for i in range(40,17,-1):
  if(i%2!=0):
    total=total+i
print(total)

319


In [ ]:
print( ord("b"))

98


In [ ]:
print( ord("A"))

65


In [ ]:
print( ord("1"))

49


In [ ]:
print(chr(97))

a


In [ ]:
print(chr(65))

A


In [ ]:
x="yash"
for i in x:   # x= iterable (direct for loop)
  print(i)

y
a
s
h


In [ ]:
x="yash"
for i in range(0,4):
  print(i)

0
1
2
3


In [ ]:
data="yash"
for i in range(0,4):
  print(i,data[i])

0 y
1 a
2 s
3 h


In [ ]:
data="SAINIMURARI"
len(data)

11

In [ ]:
data="HEYUSERABC"
for i in range(0,10):
  print(i,data[i])

0 H
1 E
2 Y
3 U
4 S
5 E
6 R
7 A
8 B
9 C


In [ ]:
data="HEYUSERABCD"
for i in  range(0,len(data)):
  print(i,data[i])

0 H
1 E
2 Y
3 U
4 S
5 E
6 R
7 A
8 B
9 C
10 D


In [ ]:
192//10
19//10
1//10

0

In [ ]:





#  days   5


#28/04/2025


#for loop
# while loop






In [ ]:
'''
for i in range(1,5):



  while(condiction):  #condiction =true
    statement

In [ ]:
i=1
while(i<5):
  print("hi")
  i=i+1

hi
hi
hi
hi


In [ ]:
i=3
total=0
while(i<77):
  total=total+i
  print(i,total)
  i+=1


3 3
4 7
5 12
6 18
7 25
8 33
9 42
10 52
11 63
12 75
13 88
14 102
15 117
16 133
17 150
18 168
19 187
20 207
21 228
22 250
23 273
24 297
25 322
26 348
27 375
28 403
29 432
30 462
31 493
32 525
33 558
34 592
35 627
36 663
37 700
38 738
39 777
40 817
41 858
42 900
43 943
44 987
45 1032
46 1078
47 1125
48 1173
49 1222
50 1272
51 1323
52 1375
53 1428
54 1482
55 1537
56 1593
57 1650
58 1708
59 1767
60 1827
61 1888
62 1950
63 2013
64 2077
65 2142
66 2208
67 2275
68 2343
69 2412
70 2482
71 2553
72 2625
73 2698
74 2772
75 2847
76 2923


In [ ]:
num=2379
while(num>0):
  rem=num%10
  num=num//10
  print(rem,num)

9 237
7 23
3 2
2 0


In [ ]:
i=80
while(i>=20):
  if(i%7==0):
    print("hey",i)
  i-=1

hey 77
hey 70
hey 63
hey 56
hey 49
hey 42
hey 35
hey 28
hey 21


In [ ]:
i=80
while(i>=20):
  if(i%7==00):
    print(i)
  i=i-1

77
70
63
56
49
42
35
28
21


In [ ]:
print("hello worlld")

hello worlld


In [ ]:
i=1
count=0
sum=0
while(i<151):
  if(i%2!=0):
    sum=sum+i
    count=count+1
    print(i,sum,count)
  i+=1



1 1 1
3 4 2
5 9 3
7 16 4
9 25 5
11 36 6
13 49 7
15 64 8
17 81 9
19 100 10
21 121 11
23 144 12
25 169 13
27 196 14
29 225 15
31 256 16
33 289 17
35 324 18
37 361 19
39 400 20
41 441 21
43 484 22
45 529 23
47 576 24
49 625 25
51 676 26
53 729 27
55 784 28
57 841 29
59 900 30
61 961 31
63 1024 32
65 1089 33
67 1156 34
69 1225 35
71 1296 36
73 1369 37
75 1444 38
77 1521 39
79 1600 40
81 1681 41
83 1764 42
85 1849 43
87 1936 44
89 2025 45
91 2116 46
93 2209 47
95 2304 48
97 2401 49
99 2500 50
101 2601 51
103 2704 52
105 2809 53
107 2916 54
109 3025 55
111 3136 56
113 3249 57
115 3364 58
117 3481 59
119 3600 60
121 3721 61
123 3844 62
125 3969 63
127 4096 64
129 4225 65
131 4356 66
133 4489 67
135 4624 68
137 4761 69
139 4900 70
141 5041 71
143 5184 72
145 5329 73
147 5476 74
149 5625 75


In [ ]:
#factor
num=8
i=1
while(i<=num):
  if(num%i==0):
    print("factor=",i)
  i+=1

factor= 1
factor= 2
factor= 4
factor= 8


In [ ]:
# breck

for i in range(1,6):
  print(i)
  break

print("----outside loop----")


1
----outside loop----


In [ ]:

for i in range(1,6):
  if(i==3):
    break
  print(i)

print("--outside loop--")

1
2
--outside loop--


In [ ]:
# continue

for i in range(1,6):
  if(i==3):
    continue
  print(i)

print("--outside loop--")

1
2
4
5
--outside loop--


In [ ]:
# continue
total=0
for i in range(1,100):
  if(i%2==0 or i%3==0):
    continue
  total=total+i
  print(i)

print("--outside loop--",total)

1
5
7
11
13
17
19
23
25
29
31
35
37
41
43
47
49
53
55
59
61
65
67
71
73
77
79
83
85
89
91
95
97
--outside loop-- 1633


In [ ]:
num=8
count=0
for i in range(1,num+1):
  if(num%i==0):
    count+=1


    print("---outside loop---",count)


---outside loop--- 1
---outside loop--- 2
---outside loop--- 3
---outside loop--- 4


In [ ]:
num=5
count=0
for i in range(1,num+1):
  if(num%i==0):
    count+=1


  print("---outside loop---",count)
  if(count>2):
    print("not a PRIME")
  else:
     print("prime")

---outside loop--- 1
prime
---outside loop--- 1
prime
---outside loop--- 1
prime
---outside loop--- 1
prime
---outside loop--- 2
prime


In [ ]:
num=153
x=num
total=0
while(num>0):
  rem=num%10
  num=num//10
  total=total+rem**3
  print(rem**3,num,total)

if(total==x):
  print("armstrong")




27 15 27
125 1 152
1 0 153
armstrong


In [ ]:


#  pattern



In [ ]:
for i in range(1,5):
  for j in range(1,5):
    print("*",end=" ")

* * * * * * * * * * * * * * * * 

In [ ]:
for i in range(4, 0, -1):
    for j in range(i):
        print(5, end=" ")
    print()


5 5 5 5 
5 5 5 
5 5 
5 


In [ ]:


#  nesxted loop



In [ ]:
num=7
for i in range(1,num+1):
  if(num%i==0):
    print("factor=",i)

factor= 1
factor= 7


In [ ]:
x = 0
for i in range(3, 0, -1):
    for j in range(1, 4):
        if i == 2:
            break
        x += i
print(x)

12


In [ ]:
s = 0
for i in range(10, 0, -2):
    s += i
print(s)

30


In [ ]:
num=8
for i in range(1,num+1):
  if(num%i==0):
    print("factor=",i)

factor= 1
factor= 2
factor= 4
factor= 8


In [ ]:
for num in range(2,8):
  for i in range(1,num+1):
    if(num%i==0):
      print("factor=",i)
  print("---")

factor= 1
factor= 2
---
factor= 1
factor= 3
---
factor= 1
factor= 2
factor= 4
---
factor= 1
factor= 5
---
factor= 1
factor= 2
factor= 3
factor= 6
---
factor= 1
factor= 7
---


In [ ]:
num=153
total=0
x=num
while(num>0):
  rem=num%10
  num=num//10
  total=total+rem**3
  print(rem**3,num,total)

if(total==x):
  print("armstrong")
else:
  print("not armstrong")


27 15 27
125 1 152
1 0 153
armstrong


In [ ]:
num=154
total=0
x=num
while(num>0):
  rem=num%10
  num=num//10
  total=total+rem**3
  print(rem**3,num,total)

if(total==x):
  print("armstrong")
else:
  print("not armstrong")

64 15 64
125 1 189
1 0 190
not armstrong


In [ ]:

for num in range(150,401):
  total=0
  x=num
  while(num>0):
    rem=num%10
    num=num//10
    total=total+rem**3


if(total==x):
  print("--armstrong--",x)


In [ ]:
# narcissists number

#153  = 1**3+4**3+3**3
#1634 = 1**4 + 6**4 + 3**4 + 4**4





In [ ]:



#pattern




In [ ]:
 for i in range(1,6):
  for j in range(1,4):
    print("*",end=" ")


  print("")

* * * 
* * * 
* * * 
* * * 
* * * 


In [ ]:
 for i in range(1,5):
  for j in range(1,5):
    print("*",end=" ")


  print("")

* * * * 
* * * * 
* * * * 
* * * * 


In [ ]:
 for i in range(1,5):
  for j in range(1,5):
    print("1",end=" ")


  print("")

1 1 1 1 
1 1 1 1 
1 1 1 1 
1 1 1 1 


In [ ]:
 for i in range(4):
  for j in range(4):
    print("1",end=" ")


  print("")

1 1 1 1 
1 1 1 1 
1 1 1 1 
1 1 1 1 


In [ ]:
 for i in range(1,6):
  for j in range(1,2):
    print("1 2 3 4  ",end=" ")


  print("")

1 2 3 4   
1 2 3 4   
1 2 3 4   
1 2 3 4   
1 2 3 4   


In [ ]:
 for i in range(4):
  for j in range(1,5):
    print(j,end=" ")


  print("")

1 2 3 4 
1 2 3 4 
1 2 3 4 
1 2 3 4 


In [ ]:
for i in range(1,5):
  for j in range(1,5):
    print(i,end=" ")


  print("")

1 1 1 1 
2 2 2 2 
3 3 3 3 
4 4 4 4 


In [ ]:
for i in range(1,5):
  for j in range(1,5):
    print(j,end=" ")


  print("")

1 2 3 4 
1 2 3 4 
1 2 3 4 
1 2 3 4 


In [ ]:
for i in range(4,0,-1):
  for j in range(1,5):
    print(i,end=" ")


  print("")

4 4 4 4 
3 3 3 3 
2 2 2 2 
1 1 1 1 


In [ ]:
for i in range(1,5):
  for j in range(5,9):
    print(j,end=" ")


  print("")

5 6 7 8 
5 6 7 8 
5 6 7 8 
5 6 7 8 


In [ ]:

num=1
for i in range(1,4):
  for j in range(1,4):
    print(num,end=" ")
    num+=1


  print("")

1 2 3 
4 5 6 
7 8 9 


In [ ]:
 for i in range(3):
  for j in range(1):
    print(65,66,67,end=" ")


  print("")

65 66 67 
65 66 67 
65 66 67 


In [ ]:
 for i in range(1,6):
  for j in range(1,i+1):
    print("*",end=" ")


  print("")

* 
* * 
* * * 
* * * * 
* * * * * 


In [ ]:
 for i in range(1,6):
  for j in range(i):
    print(i,end=" ")


  print("")

1 
2 2 
3 3 3 
4 4 4 4 
5 5 5 5 5 


In [ ]:
 num=5
 for i in range(1,4):
  for j in range(i):
    print(num,end=" ")
    num=num+1


  print("")

5 
6 7 
8 9 10 


In [ ]:
num = 5

for i in range(1, 4):
    for j in range(i):
        print(num, end="")
    print()
    num += 1


5
66
777


In [ ]:
for i in range(1, 4):
    for j in range(65, 65 + i):
        print(chr(j), end="")
    print()


A
AB
ABC


In [ ]:
char = 65

for i in range(1, 4):
    for j in range(i):
        print(chr(char), end=" ")
        char += 1
    print()


A 
B C 
D E F 


In [ ]:
 for i in range(1,6):
  for j in range(i,6):
    print("*",end=" ")


  print("")

* * * * * 
* * * * 
* * * 
* * 
* 


In [ ]:
 for i in range(1,6):
  for j in range(i,6):
    print(i,end=" ")


  print("")

1 1 1 1 1 
2 2 2 2 
3 3 3 
4 4 
5 


In [ ]:
 for i in range(1,6):
  for j in range(i,6):
    print(j,end=" ")


  print("")

1 2 3 4 5 
2 3 4 5 
3 4 5 
4 5 
5 


In [ ]:
 for i in range(1,10):
  for j in range(i,10):
    print(j,end=" ")
    i+=1

  print("")

1 2 3 4 5 6 7 8 9 
2 3 4 5 6 7 8 9 
3 4 5 6 7 8 9 
4 5 6 7 8 9 
5 6 7 8 9 
6 7 8 9 
7 8 9 
8 9 
9 


In [ ]:
#


#pattern

#06/05/2025



In [ ]:
for i in range(1,5):
  for j in range(i,4):
    print("-",end=" ")
  for j in range(1,i+1):
    print("*",end=" ")
  print("")

- - - * 
- - * * 
- * * * 
* * * * 


In [ ]:
for i in range(1,5):
  for j in range(1,i):
    print("-",end=" ")
  for j in range(i,5):
    print("*",end=" ")
  print("")

* * * * 
- * * * 
- - * * 
- - - * 


In [ ]:
for i in range(1, 6):  # Outer loop for rows (1 to 5)
    for j in range(i, 5):  # Printing leading dashes
        print("-", end="")

    for k in range(1, i + 1):  # Inner loop for numbers/spaces
        if k == 1 or i == 5 or i == k:
            print(k, end=" ")  # Print number at the borders
        else:
            print(" ", end=" ")  # Print space in between
    print()  # Move to the next line

----1 
---1 2 
--1   3 
-1     4 
1 2 3 4 5 


In [ ]:
'''



list - mutable datatype

'''

In [ ]:
#  list
# datatype = multiple value are stored together
# value can be any datatype
# list have element based on index position



In [ ]:
mylist=[10,20,30,40,9]
mylist[0]=99      # update list element
mylist.append("abc")
print(mylist)

[99, 20, 30, 40, 9, 'abc']


In [ ]:
mylist=[10,20,30,40,9]
mylist.extend([102,12,21])  # extend required iterble      # multiple vale add
print(mylist)

[10, 20, 30, 40, 9, 102, 12, 21]


In [ ]:
mylist=[10,20,30,40,9]
mylist.extend([102,12,21])
mylist.extend("hey")
print(mylist)

[10, 20, 30, 40, 9, 102, 12, 21, 'h', 'e', 'y']


In [ ]:
mylist=[10,20,30,40,9]
mylist.pop()    # delete last value
print(mylist)

[10, 20, 30, 40]


In [ ]:
mylist=[10,20,30,40,9]
mylist.pop(3)
print(mylist)

[10, 20, 30, 9]


In [ ]:
mylist=[10,20,30,40,9]
mylist.remove(30)     # in remove function pass the value not index value
print(mylist)

[10, 20, 40, 9]


In [ ]:
mylist=[10,20,30,40]
for i in range(0,4):
  print(i,mylist[i])

0 10
1 20
2 30
3 40


In [ ]:
mylist=[10,20,30,40]
for i in range(0,4):
  if(i%2==0):
    print(i,mylist[i])

0 10
2 30


In [ ]:
mylist=[10,20,30,40]
for i in range(0,4):
  if(i%2==0 and i%7==0):
    print(i,mylist[i])

0 10


In [ ]:
# find the maximum number from the list
mylist=[10,19,50,20,30,40]
maximum_number=max(mylist)
print(maximum_number)


50


In [ ]:
# find the maximum number from the list
mylist=[10,19,50,20,30,40]
maxi=mylist[0]
for i in range(0,len(mylist)):
  if(mylist[i]>maxi):
    maxi=mylist[i]
print(maxi)

50


In [ ]:
# minimum number
mylist=[10,19,50,20,30,40]
min=mylist[0]
for i in range(0,len(mylist)):
  if(mylist[i]<min):
    min=mylist[i]
print(min)

10


In [ ]:


mylist=[10,20,30,40,5,6,7]
start=0
end=len(mylist)-1
mid=len(mylist)//2
while(start<mid):
  print(mylist[start] ,mylist[end])
  start+=1
  end-=1

10 7
20 6
30 5


In [ ]:
# [10,20,30,40] swap this list
mylist=[10,20,30,40,5,6,7]
start=0
end=len(mylist)-1
mid=len(mylist)//2
while(start<mid):
  temp=mylist[start]
  mylist[start]=mylist[end]
  mylist[end]=temp
  start+=1
  end-=1
print(mylist)

[7, 6, 5, 40, 30, 20, 10]


In [ ]:


# days ===

#   07/05/2025





In [ ]:
mark=[10,20,30,40]
mark.append(50)
x=mark
print(mark)

[10, 20, 30, 40, 50]


In [ ]:
mark=[10,20,30,40]

for i in range(0,4):
  print(i,mark[3])

0 40
1 40
2 40
3 40


In [ ]:
mark=[10,20,301,40,5]

for i in range(0,4):
  if(mark[i]%2==0):
    print(i,mark[i])

0 10
1 20
3 40


In [ ]:

mark=[10,20,30,40,10,20,40]
# two pointer approch
for i in range(0,len(mark)):
  print("---",mark[i])
  for j in range(i+1,len(mark)):
    if(mark[i]==mark[j]):
      print("duplicate element",mark[i])



--- 10
duplicate element 10
--- 20
duplicate element 20
--- 30
--- 40
duplicate element 40
--- 10
--- 20
--- 40


In [ ]:
mark=[10,20,30,40,10]
temp=mark[0]
for i in range(0,len(mark)):
  if(temp==mark[i]):
    print("duplicate element",mark[i])


duplicate element 10
duplicate element 10


In [ ]:
mark=[10,20,30,20,10,50,30]

for i in range(0,len(mark)):
  print("---",mark[i])
  count=1
  for j in range(i+1,len(mark)):
    if(mark[i]==mark[j]):
      count+=1
      print("duplicate element",mark[i],count)


--- 10
duplicate element 10 2
--- 20
duplicate element 20 2
--- 30
duplicate element 30 2
--- 20
--- 10
--- 50
--- 30


In [ ]:
# target=13
# n
# n-1=>n2
mylist=[0,1,2,5,11,15]
start=0
end=len(mylist)-1
while(start<end):
  if(mylist[start]+mylist[end]==13):
    print("value",   mylist[start],mylist[end])
    break
  elif(mylist[start] + mylist[end]<13):
      start+=1
  else:
      end-=1




value 2 11


In [ ]:
# day remain

In [ ]:
#


# day=


# date =09/05/2024




In [ ]:
# tuple = datatyype, multiple value
#  immutasble


In [ ]:
x=10,20,30
print(type(x))

<class 'tuple'>


In [ ]:
x=10,20,30       # immutabe
x[0]=25


TypeError: 'tuple' object does not support item assignment

In [ ]:
x=(10,20,30,40)
x.count(10)
# x.index(20)  = return index position of the element

1

In [ ]:
# dictionary  = datatype  key:value
#dictionary don't have any index o(1)
# key = unique
# value = unique/duplicate

#  ["murari.10,30,40"]   # insert , delete o(n)
# (n)

mydictionary={10:"murari", 11:"naina", 98:"abc"}


In [ ]:
mydictionary={10:"murari", 11:"naina", 98:"abc"}
mydictionary[11]

'naina'

In [ ]:
mydictionary={10:"murari", 11:"naina", 98:"abc"}
mydictionary[11]="india"   #updte the value
print(mydictionary)

{10: 'murari', 11: 'india', 98: 'abc'}


In [ ]:
mydictionary={10:"murari", 11:"naina", 98:"abc"}
mydictionary[11]="india"   #updte the value
mydictiona[16]="saini"
print(mydictionary)

# dictionary are ordered collection of element

In [ ]:
mydictionary={10:"murari", 11:"naina", 98:"abc"}
mydictionary[11]="india"   #updte the value
mydictionary[16]="saini"
print(mydictionary)
mydictionary.pop(10)
print("after=",mydictionary)

{10: 'murari', 11: 'india', 98: 'abc', 16: 'saini'}
after= {11: 'india', 98: 'abc', 16: 'saini'}


In [ ]:
mydictionary={}
mydictionary["salary"]=1000
print(mydictionary)

{'salary': 1000}


In [ ]:
mydictionary={11:"abc",12:"def"}


x=mydictionary.popitem()
print(mydictionary)



{11: 'abc'}


In [ ]:
x

(12, 'def')

In [ ]:
mydictionary={11:"abc",12:"def"}
mydictionary.keys()
mydictionary.values()
mydictionary.items()

dict_items([(11, 'abc'), (12, 'def')])

In [ ]:
mydictionary.items()   #[(key,value) , (key,values)]

dict_items([(11, 'abc'), (12, 'def')])

In [ ]:
mydictionary.items()

dict_items([(11, 'abc'), (12, 'def')])

In [ ]:
mydictionary={11:"abc",12:"def","salary":1999}
for i in mydictionary:
  print(i,mydictionary[i])

11 abc
12 def
salary 1999


In [ ]:
mydictionary={11:"abc",12:"def","salary":1999}
for i in mydictionary.values():
  print(i)

abc
def
1999


In [ ]:
mydictionary={11:"abc",12:"def","salary":1999}
for i in mydictionary.keys():
  print(i)

11
12
salary


In [ ]:
mydictionary={11:"abc",12:"def","salary":1999}
for i in mydictionary.items():
  print(i)

(11, 'abc')
(12, 'def')
('salary', 1999)


In [ ]:
s="hello"
# {"total":5}


In [ ]:
s="hello"
count=0
for i in s:
  count+=1

{"total":count}


{'total': 5}

In [ ]:
mymarks={"amount":10,"name":"aman"}

mymarks["amount"]=mymarks["amount"]+1
print(mymarks)


{'amount': 11, 'name': 'aman'}


In [ ]:
mydictionary={"total":0}
for i in "hello":
  mydictionary["total"]=mydictionary["total"]+1

print(mydictionary)

{'total': 5}


In [ ]:
mylist=[1,2,4,7,11,19]
target=9
for x in mylist:
  if(target-x in mylist):
    print(x,target-x)

2 7
7 2


In [2]:
mydictionary={}  # {1:0 ,2:1, 4:2}
# mydictionary[key]=value
mylist=[1,2,4,7,11,19]
for i in range(0,len(mylist)):
  mydictionary[mylist[i]]=i
print(mydictionary)

{1: 0, 2: 1, 4: 2, 7: 3, 11: 4, 19: 5}


In [5]:
mylist = [1, 2, 4, 7, 11, 19]
mydictionary = {}
target = 9

# Build dictionary: value -> index
for i in range(len(mylist)):
    mydictionary[mylist[i]] = i

print("Dictionary:", mydictionary)

# Find two numbers that sum to target
for x in mylist:
    y = target - x
    if y in mydictionary and mydictionary[y] != mylist.index(x):
        print(f"Pair found: {x} + {y} = {target}")
        print(f"Indices: {mylist.index(x)}, {mydictionary[y]}")
        break


Dictionary: {1: 0, 2: 1, 4: 2, 7: 3, 11: 4, 19: 5}
Pair found: 2 + 7 = 9
Indices: 1, 3


In [ ]:



#


#     set

#set= datatype
# unique
#no index position
# set are mutable

myset={1,2,3,1,1,1,1,4,5}
myset.add("abc")


In [ ]:
myset={1,2,3,1,1,1,1,4,5}
myset.add("abc")
myset.update([10,20,30,"hello"])


In [ ]:
# sets in python----->
# (1)-identification ={}
# (2)-mutable datatype ---> we can change or update value at the runtime.


In [ ]:
a={1,2,3,4}
a.add(55)
a

{1, 2, 3, 4, 55}

In [ ]:
# loops in set

a={1,345,67}
for i in a:
  print(i)

345
67
1


In [ ]:
# a ={1,2,3}+{4,5,6}
# a

In [ ]:
a ={1,2,3,4}
b={3,4,5,6}
c=a.union(b)
c

{1, 2, 3, 4, 5, 6}

In [ ]:
d=a|b
d

{1, 2, 3, 4, 5, 6}

In [ ]:
# intersection
a ={1,2,3,4}
b={3,4,5,6}
c=a.intersection(b)
c

{3, 4}

In [ ]:
d=a&b
d

{3, 4}

In [ ]:
a-b  ### it will return only set a values removing comman element

{1, 2}

In [ ]:
b-a   ###it will return only set b values removing comman element

{5, 6}

In [ ]:
a={1,2,3,4}
a.clear()
a

set()

In [ ]:
#  que--given a list of number ,remove all dduplicate values and return the uniqe element

In [7]:
a = []
size = int(input("Enter size of list: "))

for i in range(size):
    val = int(input(f"Enter value #{i + 1}: "))
    a.append(val)

print("Your list:", a)
5


Enter size of list: 2
Enter value #1: 85
Enter value #2: 47
Your list: [85, 47]


In [ ]:
#que 2--given two sets ,find the comman element between them

In [ ]:
a={1,2,3,4}
b={3,4,5,6}
a.intersection(b)

{3, 4}

In [ ]:
#que 3-given two sets ,find the that are unique to each set

In [ ]:
a={1,2,3,4}
b={3,4,5,6}
a^b

{1, 2, 5, 6}

In [ ]:
#que 4--given two sets ,find the that are only in the first set

In [ ]:
a={1,2,3,4}
b={3,4,5,6}
a-b

{1, 2}

In [ ]:
a.difference(b)

{1, 2}

In [ ]:
#que 5--given two sets ,check if the first set is a subset of the second

In [ ]:
a={1,2,3,4}
b={1,2}
b.issubset(a)

True

In [ ]:
a={1,2,3,4}
b={1,2}
a.issubset(b)

False

In [ ]:
#que 6--given multiple sets ,return a single set that contains all unique element

In [ ]:
a={1,2,3,4}
b={3,4,5,6}
c={5,6,7,8}
d=a.union(b)
e=a.union(c)
e

{1, 2, 3, 4, 5, 6, 7, 8}

In [ ]:


    # function in python


     # date==14\05\2025




In [ ]:
# function in python
# function is reuseable block of code

In [ ]:
#  type of function
#  a- pre-define function . print(),sum(),max()
# b- manually created function

# step1-def
# step2-name of function
# step3-logic for create the function
# step4-call the function(name of function)


In [ ]:
# syntex  :
# def name_of_function():
# logic
# name_of_function




In [ ]:
# que-1=create a function who add 2 numbers

def mt_add():
  a=5
  b=6
  c=a+b
  print(c)

mt_add()

11


In [ ]:
# que 2-create a function who add sum of square of a given number

In [ ]:
i=1
n=3
sum=0
while(i<=n):
  sum=sum+i**2
  i=i+1
print("total=",sum)

total= 14


In [ ]:
# def my_squ():
# i=1
# n=3
# sum=0
# while(i<=n):
#   sum=sum+i**2
#   i=i+1
# print("total=",sum)
# my_squ()


def my_squ():
    i = 1
    n = 3
    total = 0
    while i <= n:
        total = total + i**2
        i = i + 1
    print("total =", total)

my_squ()


total = 14


In [ ]:
i=1234
sum=0
while(i>0):
  digit=i%10
  sum=sum+digit
  i=i//10
print("total=",sum)

total= 10


In [ ]:
# q2 -creatw a function in which user will givwe a num and we have calcilate sum of this num


In [ ]:
def my_add():
   i=int(input("enter num :"))
   sum=0
   while(i>0):
    d=i%10
    sum=sum+d
    i=i//10
   print("total=",sum)
   my_add()



In [ ]:
# argument and parametwr

@# parameter = these are the value which we passes when we create a function
# argument == these are the value which we passes when we call a function



In [ ]:
def my_add(a,b):
  c=a+b
  print("total=",c)
my_add(3,4)

# here(a,b)-parameters
# here(3,4)-argument

total= 7


In [ ]:
#q-3= wap who can check given number is odd or even


In [ ]:
def oddeve():
  i=int(input("enter number"))
  if(i%2==0):
    print("even")
  else:
    print("odd")
oddeve()

enter number52
even


In [ ]:
# def oddeve(p):
#   if(a%2==0):
#     print("even")
#   else:
#     print("odd")
#   p= int(input("enter num"))
# oddeve(p)

def oddeve(p):
    if p % 2 == 0:
        print("even")
    else:
        print("odd")

num = int(input("Enter a number: "))
oddeve(num)


Enter a number: 85
odd


In [ ]:
# lambda function= a lambda function can take any numberr of argument but can only one expression
# syntex : lambda argument  :expression

# ex

x= lambda a :a+5
print("total value=",x(2))

total value= 7


In [ ]:

x= lambda a,b :a*b
print("total value=",x(2,5))


total value= 10


In [ ]:

x= lambda a,b,c:a+b-c
print("total value=",x(2,5,5))

total value= 2


In [ ]:
# filter function= the filter function return as iterator where the item are filtered through a
# function to test ,if the iteam is accepted return true or false

ages=[5,12,17,18,34,67,50]
def myfun(x):
  if(x<=18):
    return True
  else:
    return False
kid=list(filter(myfun,ages))
print(kid)



[5, 12, 17, 18]


In [ ]:
# map function()=the map() exccute a specific function for each item in a iterble
# the item is sent to the function as parameter


a=["3","45","89"]

#  method 1
print(a)
for i in range(len(a)):
  a[i]=int(a[i])
print(a)


# method -2(by using map function)

b=list(map(int,a))
print(b)



['3', '45', '89']
[3, 45, 89]
[3, 45, 89]


In [ ]:
# cube using map function

def cube(x):
    return x**3

num = [1, 2, 3, 4, 5]

print(list(map(cube, num)))




[1, 8, 27, 64, 125]


In [8]:
# args in function= args allows you to pass multiple positional argument to a function .it collect them into a tuple

# def add_number(*args):
#   total=sum(args)
#   print(f"sum:){total}")

# add_number(5,10,15)

def add_number(*args):
    total = sum(args)
    print(f"Sum: {total}")

add_number(5, 10, 15)





Sum: 30


In [ ]:
# **kwarge in function=


In [ ]:
def print_details(**kwargs):
  for key,value in kwargs.items():
    print(f"{key}:{value}")

print_details(name="murari",age=25,city="jhunjhunu")


name:murari
age:25
city:jhunjhunu


In [ ]:
# using args and kwargs  together

def display_info(*args,**kwargs):
  print("positional argument:",args)
  print("keyword argument:",kwargs)

display_info(1,2,3,name="murari")

positional argument: (1, 2, 3)
keyword argument: {'name': 'murari'}


In [ ]:
# require argument


In [ ]:
def greet(name):
  print(f"hello,{name}!")

greet("murari")


hello,murari!


In [ ]:
# default argument
def greet(name="guest"):
  print(f"hello,{name}!")

greet("murari")
#greet()



hello,murari!


In [ ]:
# return keyword

In [ ]:
def add(a,b):
  return a+b

result=add(5,3)
print(result)






8


In [9]:
q-1
# find the maximum number using *args
def find_max(*args):
    if not args:
        return "Error: No values provided."
    return max(args)

print(find_max())  # ➞ Error: No values provided.
    # ➞ 0




NameError: name 'q' is not defined

In [ ]:
# calculate the product of number using *args

def product(*args):
  result=1
  for num in args:
    result *=num
  return result

print(product(2,3,4))
print(product(5,5))


24
25


In [ ]:
# genrate a full name using **kwargs
def full_name(**kwargs):
    return f"{kwargs.get('first_name', 'unknown')} {kwargs.get('last_name', 'saini')}"

print(full_name(first_name="murari", last_name="sharma"))
print(full_name(first_name="rahul"))



murari sharma
rahul saini


In [ ]:
# count vowel in a given string using return

def count_vowel(string):
  vowel="aeiouAEIOU"
  return sum(1 for char in string if char in vowel)
print(count_vowel("hello world"))
print(count_vowel("python"))


3
1


In [ ]:
# list comprehension
# list comprehension in python provide a concise way to create
# they are more readble amd efficient than tradictional for loop
# syntex:

# [expression for item in iterable if condiction]

In [ ]:
# create a list of square
squares = [i**2 for i in range(1, 6)]
print(squares)




[1, 4, 9, 16, 25]


In [ ]:
# fillter even number

even=[x for x in range(10) if x %2==0]
print(even)

[0, 2, 4, 6, 8]


In [ ]:
# conver string to uppercase

name=["sam","rohit","murari"]
upper_name=[name.upper() for name in name]
print(upper_name)

['SAM', 'ROHIT', 'MURARI']


In [ ]:
# flatten a nested list

matrix=[[1,2],[3,4],[5,6]]
flattened=[num for sublist in matrix for num in sublist]
print(flattened)

[1, 2, 3, 4, 5, 6]


In [ ]:
# generate a list of tuple

pairs=[(x,y) for x in range(3) for y in range(2)]
print(pairs)

[(0, 0), (0, 1), (1, 0), (1, 1), (2, 0), (2, 1)]


In [ ]:
#   traditional way to list comprehension


In [ ]:
                      # old format

square=[]
for x in range(1,6):
  square.append(x**2)

print(square)


[1, 4, 9, 16, 25]


In [ ]:
                  # new foemat
squares=[x**2 for i in range(1,6)]
print(square)

In [ ]:
#  crate a dictionary of sqquare

square_dict ={x:x**2 for x in range(1,8)}
print(square_dict)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49}


In [ ]:
# filter even number

even_dict ={x:x**2 for x in range(10) if x%2==0}
print(even_dict)

{0: 0, 2: 4, 4: 16, 6: 36, 8: 64}


In [ ]:
# odd number

odd_dict ={x:x**2 for x in range(10) if x%2!=0}
print(odd_dict)

{1: 1, 3: 9, 5: 25, 7: 49, 9: 81}


In [ ]:
# reverse a dictionary

original={'a':1,'b':2,'c':3}
reversed_dict={v:k for k,v in original.items()}
print(reversed_dict)

{1: 'a', 2: 'b', 3: 'c'}


In [10]:
# convert list to dictionary with length

words = ["apple", "banana", "cherry"]
length_dict = {word: len(word) for word in words}
print(length_dict)


{'apple': 5, 'banana': 6, 'cherry': 6}


In [ ]:
# dictionary of conditional values

even_odd_dict={x:('even' if x%2==0 else 'odd') for x in range(1,6)}
print(even_odd_dict)

{1: 'odd', 2: 'even', 3: 'odd', 4: 'even', 5: 'odd'}


In [ ]:
# ex=1  craeteing a set of square

square={x**2 for x in range(1,6)}
print(square)

{1, 4, 9, 16, 25}


In [ ]:
#  ex=2  filtering even number


even={x for x in range(10) if x %2==0}
print(even)

{0, 2, 4, 6, 8}


In [ ]:
# ex=3 extractring unique vowel from a string

sentence="hello world"
vowel={char for char in sentence if char in "aeiou"}
print(vowel)

{'e', 'o'}


exceptional handaling[link text](https:// [link text](https://))

In [ ]:
# exceptional handling

# try==write our logic or program

# except== if the program failed then it will return statement



In [ ]:
try:
  a=5
  b=a/0
  print(b)
except Exception as e:
  print("you cannot diveded char and zerro",e)


you cannot diveded char and zerro division by zero


In [12]:
# ex==2

try:
    number = int(input("Enter a number: "))
    print(number)
except ValueError as e:
    print("You cannot enter characters, only integers are allowed.", e)


Enter a number: 54
54


In [ ]:
 # ex==3

 try:
  data={"name":"murari","subject":"math"}
  print(data["roll"])
except KeyError as e:
  print("caught a keyerror:",e)

caught a keyerror: 'roll'


In [11]:
# EX-4  HANDLING INDEXERROR

try:
    my_list = [1, 2, 3]
    print(my_list[8])  # This will raise IndexError
except IndexError as e:
    print("Caught an IndexError:", e)


Caught an IndexError: list index out of range


In [ ]:
# ex=5--handling filenotfounderror

try:
  with open("non_existent_file.txt") as file:
    content=file.read()
except FileNotFoundError as e:
  print("caught a FileNotFoundError :",e)

IndentationError: expected an indented block after 'with' statement on line 4 (<ipython-input-27-a40af54b19b4>, line 5)

In [ ]:
# one class remaning 20\05\2025

In [ ]:
# abstraction is a  concert in     oop ,that higest unanassasry details

In [ ]:
# a decoratar @ abstract method that define method in the abstract class but does not devide implimentaction .to use abstract abc class is difuculti use


In [ ]:
from abc import ABC,abstractmethod
# abstract class
class shape(ABC):
  @abstractmethod
  def area(self):
    pass  # abstract method, no implimentaction

  @abstractmethod
  def perimeter(self):
    pass  # abstract method, no implimentaction

from abc import ABC,abstractmethod
# abstract class
class shape(ABC):
  @abstractmethod
  def area(self):
    pass  # abstract method, no implimentaction

  @abstractmethod
  def perimeter(self):
    pass  # abstract method, no implimentaction

# concreate class for circule
class Circle(shape):
  def __init__(self,radius):
    self.radius=radius

  def area(self):
    return 3.14*self.radius*self.radius

  def perimeter(self):
    return 2*3.14*self.radius

    #using the classes
circle=Circle(5)
print("circle area :",circle.area())
  def area(self):
    return 3.14*self.radius*self.radius

  def perimeter(self):
    return 2*3.14*self.radius

    #using the classes
circle=circle(5)
print("circle area :",circle.area())


IndentationError: unexpected indent (<ipython-input-4-dbf9df521202>, line 37)

In [ ]:
from abc import ABC,abstractmethod
# abstract class

class payment(ABC):
  @abstractmethod
  def make_payment(self,amount):
    pass

# concreate class for credit card payment

class creditcardpayment(payment):
  def make_payment(self,amount):
    return f"credit card payment of ${amount} processed."

# concreate class for paypal payment

class paypalpayment(payment):
  def make_payment(self,amount):
    return f"credit card payment of ${amount} processed."


 # using the classes

payment1=creditcardpayment()
print(payment1.make_payment(100))

payment2=paypalpayment()
print(payment1.make_payment(100))


credit card payment of $100 processed.
credit card payment of $100 processed.


In [ ]:
payment1=creditcardpayment()
print(payment1.make_payment(100))

credit card payment of $100 processed.


In [ ]:
# incapsuaction in oops
# incapsuaction the bundaling data and function that work on data into a single unity useally a class


In [ ]:
# there are two type
#1> public attribute
#2>private attribute

In [ ]:
#  incapsulaction imprtant because it improvr data security by restric unathorize access it parmote modularity by hidding implimentaction detaile it unable control over data by providing control access method it inhanse core maintabliti and reuseablity by pritecting data from modificati#on

In [ ]:
# example

class bankaccount:
  def_init_(self,account_holder,balance):
    self._account_holder=account_holder  # private attribute
    self._balance=balance                 # private attribute

 # gettter for account holder

 def get_account_holder(self):
  return self._account_holder

  #getter for balance

   def get_balance(self):
    return self._balance

    # method to deposite mony

    def deposite(self,amount):
      if amount >0:
        self._balance +=amount


In [ ]:
|# Student data

class Student:
    def __init__(self, name, grade):
        self.name = name                # public attribute
        self.__grade = grade            # private attribute

    # getter for grade
    def get_grade(self):
        return self.__grade

    # setter for grade (with validation)
    def set_grade(self, new_grade):
        if 0 <= new_grade <= 100:
            self.__grade = new_grade
            return "Grade updated successfully!"
        else:
            return "Invalid grade! Must be between 0 and 100."


# using the class
student = Student("Rohit", 85)
print(student.name)                 # public attribute
print(student.get_grade())         # using getter
print(student.set_grade(55))       # using setter
print(student.get_grade())         # updated value





SyntaxError: invalid syntax (<ipython-input-22-c77e998ca076>, line 1)

In [ ]:
# recooresiion in python refer to A PROCESS where a function call itself .


# recurrison use in class to perform to perform repet task

# feature in recurrsion ---
# case-1
# case-2


# 1>base case=a condiction that stop the recursion is prevent infinite class
# 2> recrusive case = that part where the function clll itself with the modified argument.



In [ ]:
class BankAccount:
    def _init_(self, holder_name, balance=0):
        self.holder_name = holder_name
        self.balance = balance

    def deposit(self, amount):
        if amount > 0:
            self.balance += amount
            print(f"{amount}{self.balance}")

    def withdraw(self, amount):
        if amount > 0 and amount <= self.balance:
            self.balance -= amount
            print(f"{amount} {self.balance}")
        else:
            print("enfaluance balance")

    def check_balance(self):
        print(f": {self.balanacc1=deposit(500)

In [ ]:
class student:
  def_init_(self,name):
    self.name=name
    self_score=[]

  def add_score(self,score):
    if 0<=score <=100:
      self__

introduction to numpy

In [ ]:
# introduction to numpy===>
# numpy is a open source library is used for scintific calculation

In [ ]:
#  how numpy is better than list  !

#(1)= numpy is honogeneous data type while list is hetrogenous data type.
#(2)= numpy take less memory while list take more memory.
#(3)= numpy take lesss exicution time while list take more exicution time .


In [ ]:
pip install numpy

In [ ]:
import numpy as np

In [ ]:
a=[1,45,78,90]
type(a)
b=np.array(a)
b

array([ 1, 45, 78, 90])

In [ ]:
a=[]
size =int(input("enter size :"))
for i in range(size):
  val=int(input("enter element:"))
  a.append(val)

  print(a)

  b=np.array(a)
  b

enter size :3
enter element:12
[12]
enter element:45
[12, 45]
enter element:78
[12, 45, 78]


In [ ]:
type(b)

numpy.ndarray

In [ ]:
a=[[1,2,3,4],[4,5,6,7],[7,8,9,5]]
a

[[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 5]]

In [ ]:
b=np.array(a)
b

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [7, 8, 9, 5]])

In [ ]:
print("total row and column :",b.shape) # shape =n(rows),n(column)
print("total element:",b.size)  # size =total element =n(rows)*n(column)
print("total dimension:",b.ndim)  # ndim=stand for n_dimensional

total row and column : (3, 4)
total element: 12
total dimension: 2


In [ ]:
# function in numpy

In [ ]:
#  (1). zeros()-----> it will create an arrey in which all the value in either one dimensional or multi dimensinal will be 0.


In [ ]:
a=np.zeros(3)
a

array([0., 0., 0.])

In [ ]:
a=np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# (2). ones()---> it will create an arrey in which all the value will be 1 in either one dimensial or multi dimensial

In [ ]:
a=np.ones(3)
a

array([1., 1., 1.])

In [ ]:
a=np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# (3)= eye()------>
# matrix----> digonal position ---->1
# it will create an array in which digonal positional element will be 1 and reset all are 0.


In [ ]:
a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a=np.eye(3,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
# (4). diag()--->
#                  it will create an array in which you can set custom values at dignol position.


In [ ]:
a=np.diag([1,45,78,90])
a

array([[ 1,  0,  0,  0],
       [ 0, 45,  0,  0],
       [ 0,  0, 78,  0],
       [ 0,  0,  0, 90]])

In [ ]:
# (5).=random modules-------> it will return random number


In [ ]:
# (a). randint()------> it will return random number in a given range.
# syntex
# np.random.randint(min_number,max_number,total_number)


In [ ]:
a=np.random.randint(1,10,3)
a

array([8, 1, 7])

In [ ]:
# (b).= rand()----> it will provide random number in range of 0 to 1.

In [ ]:
a=np.random.rand(4)
a

array([0.94710198, 0.99174409, 0.91345401, 0.77266591])

In [ ]:
# random number -----> data use -----> output
# if random number refresh update----> previous output change

In [ ]:
# (c).= seed()-----> it will fix our random generated data


In [ ]:

a=np.random.randint(1,10,3)
a

array([4, 9, 2])

In [ ]:


# view vs copy





In [ ]:
# view mean modification in original data and copy mean modification in duplicate data.

In [ ]:
a=np.array([10,20,30,40,50,60,70,80,90])
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
b=a[3:6]
b[:]=0
b

array([0, 0, 0])

In [ ]:
a

array([10, 20, 30,  0,  0,  0, 70, 80, 90])

In [ ]:
a=np.array([10,20,30,40,50,60,70,80,90])
b=a[3:6].copy()
b[:]=0
b


array([0, 0, 0])

In [ ]:
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# operation on array



In [ ]:
import numpy as np

In [ ]:
a=np.arange(1,16,1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [ ]:
b=a>10
a[b]

array([11, 12, 13, 14, 15])

In [ ]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [ ]:
a[a%2!=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [ ]:
a=np.arange(1,5)
a

array([1, 2, 3, 4])

In [ ]:
# reshaping the  array

In [ ]:
a=np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
a.shape

(12,)

In [ ]:
# 1*12 ,12*1
#2*6 ,6*2
#3*4 ,4*3

In [ ]:
a.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
a.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a.reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [ ]:
a=np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [ ]:
b=np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [ ]:
a+b  # (1+5=6 ,2+6=8, 3+7=10,4+)

array([[ 6,  8],
       [10, 12]])

In [ ]:
a-b

array([[-4, -4],
       [-4, -4]])

In [ ]:
a*b

array([[ 5, 12],
       [21, 32]])

In [ ]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [ ]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [ ]:
a

array([[1, 2],
       [3, 4]])

In [ ]:
a**2

array([[ 1,  4],
       [ 9, 16]])

In [ ]:
a**3

array([[ 1,  8],
       [27, 64]])

In [ ]:
# linspace()------> it will return same gap value in a given range

In [ ]:
a=np.linspace(1,2,5)

In [ ]:
# unique()----> it will provide an array in which it will return 3 array
# arr-----> return unique value
# return_index= true------->return indexing of unique value
# return_counts=true----->

In [ ]:
a=np.array([1,2,3,1,1,1,2,6,7])
a

array([1, 2, 3, 1, 1, 1, 2, 6, 7])

In [ ]:
np.unique(a , retuern_index=True , return_counts=True)

TypeError: unique() got an unexpected keyword argument 'retuern_index'

In [ ]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.sum(a)

np.int64(45)

In [ ]:
np.sum(a,axis=0)  # return column wise sum

array([12, 15, 18])

In [ ]:
np.sum(a,axis=1)  # return row wise

array([ 6, 15, 24])

In [ ]:
a=np.arange(1,5)
a=np.arange(5,9)
a=np.arange(9,13)
a=np.hstack()
a=np.vstack()

TypeError: hstack() missing 1 required positional argument: 'tup'

In [ ]:
# numpy  quection

In [ ]:
import numpy as np

In [ ]:
# create an array using numpy
a=[1,2,3,4,5]
type(a)
b=np.array(a)
b

array([1, 2, 3, 4, 5])

In [ ]:
# create an array of 10 random integer

In [ ]:
array=np.random.randint(1,20,10)
array

array([ 6, 19,  1, 13, 18, 12, 11, 11, 19, 14])

In [ ]:
#create an array of element fron 10-20

In [ ]:
a=np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
# create an array which contain value 5,10 time

In [ ]:
# creatw a one dimensional array and convert that into 3*3 matrix

In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9])
a=a.reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# create a 2d array of size 3*3 but all the element

pandas library

In [ ]:
'''
pandas is an open source library that is used for handle data manipulation.

'''

In [ ]:
import pandas as pd

In [ ]:
# data structure of pandas

# (1)--series===1-dimensional array and it contain only values.
# (2)--dataframe== > multi dimensional array and it contain value with column name


Series

In [ ]:
a=pd.Series([1,45,78,90])
a

0     1
1    45
2    78
3    90
dtype: int64

In [ ]:
type(a)

dict

dataFrame

In [ ]:
a={
    "emp_id":[1,2,3,4,5],
    "emp_name":["sam","raj","mohit","ankit","pallvi"],
    "domain":["it","sales","it","it","sales"],
    "working_hours":[9,8,8,9,9],
    "salary":[23000,25000,31000,36000,40000]
}

In [ ]:
type(a)

dict

In [ ]:
df=pd.DataFrame(a)
df

emp_id emp_name domain  working_hours  salary
0       1      sam     it              9   23000
1       2      raj  sales              8   25000
2       3    mohit     it              8   31000
3       4    ankit     it              9   36000
4       5   pallvi  sales              9   40000

In [ ]:
df.to_csv("/content/sample_data.csv")

import data

In [ ]:
df=pd.read_csv("/content/sample_data.csv")
df

Unnamed: 0  emp_id emp_name domain  working_hours  salary
0           0       1      sam     it              9   23000
1           1       2      raj  sales              8   25000
2           2       3    mohit     it              8   31000
3           3       4    ankit     it              9   36000
4           4       5   pallvi  sales              9   40000

In [ ]:
import pandas as pd

In [ ]:
a={
    "stu_roll_no":[1,2,3,4,5,6,7,8,9,10],
    "stu_name":["murari","jassi","vinod","parmod","parveen","ramu","dilip","banti","viju","goutam"],
    "stu_course":["mca","ba","ba","bcom","bsc","ba","bsc","ba","bcom","bsc"],
    "stu_marks":[66,55,60,65,70,50,36,58,70,85]
}

In [ ]:
type(a)

dict

In [ ]:
df=pd.DataFrame(a)

df

In [ ]:
df.to_csv("/content/stu_data.csv")

In [ ]:
df=pd.read_csv("/content/stu_data.csv")
df

Unnamed: 0  stu_roll_no stu_name stu_course  stu_marks
0           0            1   murari        mca         66
1           1            2    jassi         ba         55
2           2            3    vinod         ba         60
3           3            4   parmod       bcom         65
4           4            5  parveen        bsc         70
5           5            6     ramu         ba         50
6           6            7    dilip        bsc         36
7           7            8    banti         ba         58
8           8            9     viju       bcom         70
9           9           10   goutam        bsc         85

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv("/content/flipkart (2).csv")
#df


In [ ]:
df.head()

CGtC98 href  \
0  https://www.flipkart.com/samsung-galaxy-s25-ul...   
1  https://www.flipkart.com/nothing-phone-3a-pro-...   
2  https://www.flipkart.com/vivo-v40-pro-5g-gange...   
3  https://www.flipkart.com/samsung-galaxy-s24-5g...   
4  https://www.flipkart.com/samsung-galaxy-s25-ul...   

                                          DByuf4 src          uu79Xy  \
0  https://rukminim2.flixcart.com/image/312/312/x...  Add to Compare   
1  https://rukminim2.flixcart.com/image/312/312/x...  Add to Compare   
2  https://rukminim2.flixcart.com/image/312/312/x...  Add to Compare   
3  https://rukminim2.flixcart.com/image/312/312/x...  Add to Compare   
4  https://rukminim2.flixcart.com/image/312/312/x...  Add to Compare   

                                              KzDlHZ  XQDdHH  \
0  Samsung Galaxy S25 Ultra 5G (Titanium Black, 5...     4.7   
1              Nothing Phone (3a) Pro (Grey, 256 GB)     4.5   
2              vivo V40 Pro 5G (Ganges Blue, 512 GB)     4.5   
3     Samsung Galaxy S24+ 5G (Cobalt Violet, 256 GB)     4.5   
4  Samsung Galaxy S25 Ultra 5G (Titanium Silverbl...     4.7   

                                          Rza2QY src         Wphh3N hG7V+4  \
0  data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0...  1,695 Ratings      &   
1  data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0...  1,676 Ratings      &   
2  data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0...    875 Ratings      &   
3  data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0...  9,624 Ratings      &   
4  data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0...  1,695 Ratings      &   

      Wphh3N 2                   J+igdf  ...  \
0  203 Reviews   12 GB RAM | 512 GB ROM  ...   
1  148 Reviews   12 GB RAM | 256 GB ROM  ...   
2   99 Reviews   12 GB RAM | 512 GB ROM  ...   
3  735 Reviews   12 GB RAM | 256 GB ROM  ...   
4  203 Reviews  12 GB RAM | 1024 GB ROM  ...   

                                            J+igdf 6     Nx9bqj     yRaY8j  \
0  1 Year Manufacturer Warranty for Device and 6 ...  ₹1,29,999  ₹1,41,999   
1                      1 Year Manufacturing Warranty    ₹33,999    ₹36,999   
2  1 Year Warranty on Handset and 6 Months Warran...    ₹55,999    ₹60,999   
3  1 Year Manufacturer Warranty for Device and 6 ...    ₹52,999    ₹99,999   
4  1 Year Manufacturer Warranty for Device and 6 ...  ₹1,53,999  ₹1,65,999   

    UkUFwK         yiggsN                                        _0CSTHy src  \
0   8% off  Free delivery  https://static-assets-web.flixcart.com/fk-p-li...   
1   8% off  Free delivery  https://static-assets-web.flixcart.com/fk-p-li...   
2   8% off  Free delivery  https://static-assets-web.flixcart.com/fk-p-li...   
3  47% off  Free delivery  https://static-assets-web.flixcart.com/fk-p-li...   
4   7% off  Free delivery  https://static-assets-web.flixcart.com/fk-p-li...   

                   yiggsN 2 yiggsN 3 yiggsN 4         yiggsN 5  
0                Saver Deal     Upto  ₹45,150  Off on Exchange  
1                Saver Deal     Upto  ₹25,350  Off on Exchange  
2                Saver Deal     Upto  ₹42,300  Off on Exchange  
3  Top Discount of the Sale     Upto  ₹38,600  Off on Exchange  
4                Saver Deal     Upto  ₹45,150  Off on Exchange  

[5 rows x 24 columns]

In [ ]:
df.tail()

CGtC98 href  \
21  https://www.flipkart.com/samsung-galaxy-s25-ul...   
22  https://www.flipkart.com/vivo-v50-5g-rose-red-...   
23  https://www.flipkart.com/samsung-galaxy-s24-5g...   
24                                                NaN   
25                                                NaN   

                                           DByuf4 src          uu79Xy  \
21  https://rukminim2.flixcart.com/image/312/312/x...  Add to Compare   
22  https://rukminim2.flixcart.com/image/312/312/x...  Add to Compare   
23  https://rukminim2.flixcart.com/image/312/312/x...  Add to Compare   
24                                                NaN             NaN   
25                                                NaN             NaN   

                                               KzDlHZ  XQDdHH  \
21  Samsung Galaxy S25 Ultra 5G (Titanium Silverbl...     4.7   
22                     vivo V50 5G (Rose Red, 512 GB)     4.5   
23        Samsung Galaxy S24+ 5G (Onyx Black, 256 GB)     4.5   
24                                                NaN     NaN   
25                                                NaN     NaN   

                                           Rza2QY src         Wphh3N hG7V+4  \
21  data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0...  1,695 Ratings      &   
22  data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0...  1,401 Ratings      &   
23  data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0...  9,624 Ratings      &   
24                                                NaN            NaN    NaN   
25                                                NaN            NaN    NaN   

       Wphh3N 2                  J+igdf  ...  \
21  203 Reviews  12 GB RAM | 256 GB ROM  ...   
22  131 Reviews  12 GB RAM | 512 GB ROM  ...   
23  735 Reviews  12 GB RAM | 256 GB ROM  ...   
24          NaN                     NaN  ...   
25          NaN                     NaN  ...   

                                             J+igdf 6     Nx9bqj     yRaY8j  \
21  1 Year Manufacturer Warranty for Device and 6 ...  ₹1,17,999  ₹1,29,999   
22  1 Year Manufacturer Warranty for Device and 6 ...    ₹40,999    ₹48,999   
23  1 Year Manufacturer Warranty for Device and 6 ...    ₹52,999    ₹99,999   
24                                                NaN        NaN        NaN   
25                                                NaN        NaN        NaN   

     UkUFwK         yiggsN                                        _0CSTHy src  \
21   9% off  Free delivery  https://static-assets-web.flixcart.com/fk-p-li...   
22  16% off  Free delivery  https://static-assets-web.flixcart.com/fk-p-li...   
23  47% off  Free delivery  https://static-assets-web.flixcart.com/fk-p-li...   
24      NaN            NaN                                                NaN   
25      NaN            NaN                                                NaN   

                    yiggsN 2       yiggsN 3 yiggsN 4         yiggsN 5  
21                Saver Deal           Upto  ₹45,150  Off on Exchange  
22             Only few left           Upto  ₹31,000  Off on Exchange  
23  Top Discount of the Sale  Only few left      NaN              NaN  
24                       NaN            NaN      NaN              NaN  
25                       NaN            NaN      NaN              NaN  

[5 rows x 24 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 24 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   CGtC98 href  24 non-null     object 
 1   DByuf4 src   24 non-null     object 
 2   uu79Xy       24 non-null     object 
 3   KzDlHZ       24 non-null     object 
 4   XQDdHH       24 non-null     float64
 5   Rza2QY src   24 non-null     object 
 6   Wphh3N       24 non-null     object 
 7   hG7V+4       24 non-null     object 
 8   Wphh3N 2     24 non-null     object 
 9   J+igdf       24 non-null     object 
 10  J+igdf 2     24 non-null     object 
 11  J+igdf 3     24 non-null     object 
 12  J+igdf 4     24 non-null     object 
 13  J+igdf 5     24 non-null     object 
 14  J+igdf 6     17 non-null     object 
 15  Nx9bqj       24 non-null     object 
 16  yRaY8j       23 non-null     object 
 17  UkUFwK       23 non-null     object 
 18  yiggsN       24 non-null     object 
 19  _0CSTHy sr

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
a={
    "stu_roll_no":[1,2,3,4,5,6,7,8,9,10],
    "stu_name":["murari","jassi","vinod","parmod","parveen","ramu","dilip","banti","viju","goutam"],
    "stu_course":["mca","ba","ba","bcom","bsc","ba","bsc","ba","bcom","bsc"],
    "stu_marks":[66,55,60,65,70,50,36,58,70,85]
}

In [ ]:
df=pd.DataFrame(a)
df

stu_roll_no stu_name stu_course  stu_marks
0            1   murari        mca         66
1            2    jassi         ba         55
2            3    vinod         ba         60
3            4   parmod       bcom         65
4            5  parveen        bsc         70
5            6     ramu         ba         50
6            7    dilip        bsc         36
7            8    banti         ba         58
8            9     viju       bcom         70
9           10   goutam        bsc         85

In [ ]:
df.to_csv("/content/stu_data")

In [ ]:
df=pd.read_csv("/content/stu_data")
df

Unnamed: 0  stu_roll_no stu_name stu_course  stu_marks
0           0            1   murari        mca         66
1           1            2    jassi         ba         55
2           2            3    vinod         ba         60
3           3            4   parmod       bcom         65
4           4            5  parveen        bsc         70
5           5            6     ramu         ba         50
6           6            7    dilip        bsc         36
7           7            8    banti         ba         58
8           8            9     viju       bcom         70
9           9           10   goutam        bsc         85

In [ ]:
df.head()

Unnamed: 0  stu_roll_no stu_name stu_course  stu_marks
0           0            1   murari        mca         66
1           1            2    jassi         ba         55
2           2            3    vinod         ba         60
3           3            4   parmod       bcom         65
4           4            5  parveen        bsc         70

In [ ]:
df.tail()

Unnamed: 0  stu_roll_no stu_name stu_course  stu_marks
5           5            6     ramu         ba         50
6           6            7    dilip        bsc         36
7           7            8    banti         ba         58
8           8            9     viju       bcom         70
9           9           10   goutam        bsc         85

In [ ]:
dict={}
dict

{}